version: '3.1'
services:
  postgresql-database:
    image: postgres:12.0
    environment:
      - POSTGRES_USER=ecommerce
      - POSTGRES_PASSWORD=ecommerce
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
  redis-database:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379