spring:
  datasource:
    username: ecommerce
    password: ecommerce
    url: jdbc:postgresql://localhost:5432/ecommerce?currentSchema=ecommerce
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: false